# Site settings
title: "Ju ğŸ’ Py"
description: |
    STABLE CAFÃ‰, San Francisco

    February 2, 2019
owner: Pierre-Yves Ricau
first_published: 2018
baseurl: ""
url: "jupy.us"

# Build settings
markdown: kramdown
